### Get health of the service
GET http://localhost:8080/api/cmd/achievement/health HTTP/1.1
accept: */*
X-API-Version: 1

### Create a new Achievement

@authToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJwZWRyb2YiLCJ1c2VyS2V5IjoidHdXcnlXTSIsImVtYWlsIjoicGVkcm9mQGV4YW1wbGUuY29tIiwiZmlyc3ROYW1lIjoiVGhyb2siLCJsYXN0TmFtZSI6IkJvbmUiLCJpYXQiOjE3NTg2MDc1MjMsImV4cCI6MTc1ODY5MzkyMn0.RSvZSFRDGmmfA1GTDog3eJaWzuGJz6yns8tw2zVMbwxhNFWon-H2mTSjdtTy4IVS

POST http://localhost:8080/api/cmd/achievement HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

{
  "title": "A title for an achievement",
  "description": "This is a test for the text analyzer, now continue",
  "completedDate": "2025-09-15",
  "skills": ["int", "cha", "luc"],
  "isPublic": true
}

### Get achievement details by entityKey

GET http://localhost:8080/api/qry/achievement/detail?size=lg&entityKey=JP5HVXl HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

### Add a Comment to the Achievement
POST http://localhost:8080/api/cmd/achievement/JP5HVXl/comments HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

{
"commentText": "Best achievmeent I've ever achieved"
}

### Update an existing Achievement
PUT http://localhost:8080/api/cmd/achievement/JP5HVXl HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

{
  "title": "A new updated title",
  "description": "A new updated description",
  "skills": ["str", "dex", "int"],
  "isPublic": false
}

### Disable an existing Achievement
PATCH http://localhost:8080/api/cmd/achievement/PFBB8UQ/disable HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

### Delete an existing Achievement
DELETE http://localhost:8080/api/cmd/achievement/PFBB8UQ HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}


### Add a Celebration to the Achievement
POST http://localhost:8080/api/cmd/achievement/oYIuT8w/celebration HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

{
  "count":9
}