### Get health of the service
GET http://localhost:8080/api/cmd/achievement/health HTTP/1.1
accept: */*
X-API-Version: 1

### Create a new Achievement

@authToken = 
POST http://localhost:8080/api/cmd/achievement HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

{
  "userKey": "A3Rc2mQ",
  "title": "Completed Miilti File Upload",
  "description": "Sucessfully implemented multi file upload for achievement media.",
  "completedDate": "2025-07-18",
  "skills": ["int", "wis", "luc"],
  "isPublic": true
}

### Get achievement details by entityKey

GET http://localhost:8080/api/qry/achievement/detail?size=lg&entityKey=PFBB8UQ HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}