### Get health of the service
GET http://localhost:8080/api/cmd/achievement/health HTTP/1.1
accept: */*
X-API-Version: 1

### Create a new Achievement

@authToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJwZWRyb2YiLCJ1c2VyS2V5Ijoibnp4eGIxYiIsImVtYWlsIjoicGVkcm9mQGV4YW1wbGUuY29tIiwiZmlyc3ROYW1lIjoiRWR3aW4iLCJsYXN0TmFtZSI6IlZhbmNlIiwiaWF0IjoxNzU1NDE1NzExLCJleHAiOjE3NTU1MDIxMTF9.RuNWVxOIM87Gs3yjwPjfogl5lDZxYft0TAP2xHksszuRQjWPdcABALMZblYe7ZpL

POST http://localhost:8080/api/cmd/achievement HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

{
  "userKey": "A3Rc2mQ",
  "title": "Completed Miilti File Upload",
  "description": "Sucessfully implemented multi file upload for achievement media.",
  "completedDate": "2025-07-18",
  "skills": ["int", "wis", "luc"],
  "isPublic": true
}

### Get achievement details by entityKey

GET http://localhost:8080/api/qry/achievement/detail?size=lg&entityKey=PFBB8UQ HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

### Add a Comment to the Achievement
POST http://localhost:8080/api/cmd/achievement/comments HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

{
"achievementKey": "gCbuccA",
"userKey": "nzxxb1b",
"commentText": "This is a test comment for the achievement."
}

### Update an existing Achievement
PUT http://localhost:8080/api/cmd/achievement/PFBB8UQ HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}

{
  "achievementKey": "PFBB8UQ",
  "userKey": "nzxxb1b",
  "title": "A new updated title",
  "description": "A new updated description",
  "skills": ["str", "dex", "int"],
  "isPublic": false
}

### Disable an existing Achievement
PATCH http://localhost:8080/api/cmd/achievement/PFBB8UQ/disable HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1
Authorization: Bearer {{authToken}}