### Create a new User
POST http://localhost:8080/api/cmd/user HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1

{
  "username": "johndoe123",
  "email": "john.doe@example.com",
  "firstName": "John",
  "lastName": "Doe",
  "birthDate": "1990-05-15"
}

### Create another User
POST http://localhost:8080/api/cmd/user HTTP/1.1
Content-Type: application/json
accept: application/json
X-API-Version: 1

{
  "username": "janesmith456",
  "email": "jane.smith@example.com",
  "firstName": "Jane",
  "lastName": "Smith",
  "birthDate": "1992-08-22"
}
